# Generated by Django 3.1.3 on 2021-02-05 01:52

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_username', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('userprofilemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profile_username.userprofilemodel')),
                ('title', models.CharField(max_length=55)),
                ('content', models.CharField(max_length=8000)),
                ('likes', models.IntegerField(default=0)),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='profile_username.userprofilemodel')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('profile_username.userprofilemodel', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
